//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITACO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingrediente()
        {
            this.Producto_Tiene_Ingrediente = new HashSet<Producto_Tiene_Ingrediente>();
        }
    
        public long IdIngrediente { get; set; }
        public string NombreIngrediente { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal Cantidad { get; set; }
        public decimal ValorIngrediente { get; set; }
        public bool Estado { get; set; }
        public string IdMedida { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public int IdTipoCantidad { get; set; }
    
        public virtual TipoCantidad TipoCantidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Tiene_Ingrediente> Producto_Tiene_Ingrediente { get; set; }
    }
}
